apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-prometheus

resources:
  - crds.yaml
  - namespace.yaml
  - resources.yaml
  - serviceaccount-prometheus.yaml
  - clusterrole-prometheus.yaml
  - clusterrolebinding-prometheus.yaml
  - service-prometheus-main.yaml
  - prometheus.yaml
  - alertmanager.yaml
  - ingress-alertmanager.yaml
  - ingress-prometheus.yaml
  - cert-alertmanager.yaml
  - cert-prometheus.yaml
