---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
spec:
  externalUrl: https://prometheus.example.com
  serviceAccountName: prometheus
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  alerting:
    alertmanagers:
      - namespace: infra-prometheus
        name: main
        port: web
