apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - ../../../../kutomize/components/cert-manager

patches:
  - path: cluster-issuer-smallstep.yaml
