name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  enumerate-folders:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          # Finds directories and converts to JSON array
          DIRS=$(find . -type f -name "kustomization.yaml" -printf "%h\n" | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$DIRS" >> $GITHUB_OUTPUT
  lint:
    needs: enumerate-folders
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.enumerate-folders.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install yamllint
        run: |
          python -m pip install yamllint

      - name: Lint {{ matrix.directory }}
        run: yamllint -c ./.yamllint "${{ matrix.directory }}"
